/*
******************************************************************************
File:		main.c
Info:		Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-02-23
Author:		Ku, Do Yeou
******************************************************************************
*/

/* Standard includes. */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"

/* Task includes. */
#include "tasks/memory.h"

/* FATFS includes. */
#include "fatfs/ff.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	/* Initialize LEDs */
	STM_EVAL_LEDInit(LED3);
	STM_EVAL_LEDInit(LED4);
	STM_EVAL_LEDInit(LED5);
	STM_EVAL_LEDInit(LED6);

	/* Turn off LEDs */
	STM_EVAL_LEDOff(LED3);
	STM_EVAL_LEDOff(LED4);
	STM_EVAL_LEDOff(LED5);
	STM_EVAL_LEDOff(LED6);

	/* FATFS */
	char status = 0;
	FATFS file_system;
	FIL file_pointer;
	UINT bytes_written;
	FLAG file_flag;
	FRESULT f_err_code;

	/*
	 * filename	:	less than 13 characters with last character being NULL
	 * data		:	recommend to use DMA and buffer if to store in a loop
	 */
	char filename[13] = "test.txt\0";
	char mydata[] = "reference: (C) ChaN, 2007 & (C) Martin Thomas, 2010";

	/* Check if SD is okay and accessible */
	status = check_memory (
			&file_system,
			&file_pointer,
			f_err_code);

	/* Default set-up of FLAG. See memory.h/c to understand. */
	file_flag.log_enabled = 1;
	file_flag.file_opened = 0;
	file_flag.filename_ok = PASS;

	/* If SD is okay, write to SD */
	if (status == SD_CARD_OK){
		for (int i = 2; i > 0; i--){
			status = write_to_memory (
					&file_system,
					&file_pointer,
					f_err_code,
					filename,
					&bytes_written,
					mydata,
					sizeof(mydata),
					&file_flag);
		}
	}
	f_close(&file_pointer);
	file_flag.file_opened = 0;

	while (1)
	{
		STM_EVAL_LEDToggle (LED3);
	}
}


/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
  /* TODO, implement your code here */
  return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
  /* TODO, implement your code here */
  return -1;
}
