/*
******************************************************************************
File:		main.c
Info:		Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-03-07
Author:		Ku, Do Yeou
******************************************************************************
*/

#include "main.h"

int main(void)
{
	/* Initialize LEDs */
	STM_EVAL_LEDInit(LED3);	STM_EVAL_LEDInit(LED4);	STM_EVAL_LEDInit(LED5);	STM_EVAL_LEDInit(LED6);

	/* Turn off LEDs */
	STM_EVAL_LEDOff(LED3);	STM_EVAL_LEDOff(LED4);	STM_EVAL_LEDOff(LED5);	STM_EVAL_LEDOff(LED6);

	SCONFIG sensor_config;
	sensor_config.accel_rate	=	ACC_PMU_ODR_1000;
	sensor_config.accel_range	=	ACC_PMU_RANGE_16;
	sensor_config.gyro_rate		=	GYRO_ODR_1000;
	sensor_config.gyro_range	=	GYRO_RANGE_RANGE_2000;
	sensor_config.mag_rate		=	MAG_PWR_CR2_ODR_20;
	sensor_config.mag_range_xy	=	MAG_REP_XY_HIGH_ACCURACY_PRESET_REPXY;
	sensor_config.mag_range_z	=	MAG_REP_Z_HIGH_ACCURACY_PRESET_REPZ;

	SSTATUS sensor_status;
	sensor_status	=	sensor_initialize(&sensor_config);

	if(sensor_status == SENS_OK)	STM_EVAL_LEDOn(LED3);
	else							STM_EVAL_LEDOn(LED6);
	/* Infinite loop */
	while (1)
	{
		int i = 0;
		STM_EVAL_LEDOn(LED4);
		i++;

		STM_EVAL_LEDOff(LED4);
		i++;
	}
}
