/*
******************************************************************************
File:		main.c
Info:		Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-02-23
Author:		Ku, Do Yeou
******************************************************************************
*/

#include "main.h"

int main(void)
{
	/* Initialize EXTI */
	exti_initialize();

	/* Initialize LEDs */
	STM_EVAL_LEDInit(LED3);	STM_EVAL_LEDInit(LED4);	STM_EVAL_LEDInit(LED5);	STM_EVAL_LEDInit(LED6);

	/* Turn off LEDs */
	STM_EVAL_LEDOff(LED3);	STM_EVAL_LEDOff(LED4);	STM_EVAL_LEDOff(LED5);	STM_EVAL_LEDOff(LED6);

	/* FATFS */
	FATFS file_system;
	FIL file_pointer;
	UINT bytes_written;
	FRESULT f_err_code;

	/* Default set-up of FLAG. See memory.h/c to understand. */
	file_flag.log_enabled = 1;
	file_flag.file_opened = 0;
	file_flag.filename_ok = PASS;

	/*
	 * status	:	indicates memory_status and logging_status
	 * filename	:	less than 13 characters with last character being NULL
	 * data		:	recommend to use DMA and buffer if to store in a loop
	 */
	char status = 0;
	char filename[13] = "b_test.bin\0";
	for (int i = 0; i < 50 ;i++)mydata[i] = 0xFA;

	/* Check if SD is okay and accessible */
	while(status != SD_CARD_OK){
		status = check_memory (
				&file_system,
				&file_pointer,
				f_err_code);
	}

	for (int i = 0; i < 50; i++){
		status = write_to_memory (
				&file_system,
				&file_pointer,
				f_err_code,
				filename,
				&bytes_written,
				mydata,
				sizeof(mydata),
				&file_flag);
	}

	f_close(&file_pointer);
	file_flag.file_opened = 0;

	while (1)
	{
		if(status == SD_CARD_OK|LOGGING_ON) STM_EVAL_LEDOn(LED3);
	}
}

