/*
******************************************************************************
File:		main.c
Info:		Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-03-12
Author:		Ku, Do Yeou
******************************************************************************
*/

#include "main.h"

int main(void)
{
	/* Initialize LEDs : Off */
	STM_EVAL_LEDInit(LED3);	STM_EVAL_LEDInit(LED4);	STM_EVAL_LEDInit(LED5);	STM_EVAL_LEDInit(LED6);
	STM_EVAL_LEDOff(LED3);	STM_EVAL_LEDOff(LED4);	STM_EVAL_LEDOff(LED5);	STM_EVAL_LEDOff(LED6);

	/* Initialize FATFS */
	FATFS file_system;
	FIL file_pointer;
	FRESULT f_err_code = FR_OK;
	UINT bytes_written;

	file_flag.log_enabled = 1;
	file_flag.file_opened = 0;
	file_flag.filename_ok = PASS;
	char status = 0;
	char filename[13] = "s_test.bin\0";
	char dummy [] = "end";

	while(status != SD_CARD_OK){
		status = check_memory (
				&file_system,
				&file_pointer,
				f_err_code);
	}if (status) { ; }

	/* Initialize Sensors */
	SCONFIG sensor_config;
	sensor_config.accel_rate	=	ACC_PMU_ODR_1000;
	sensor_config.accel_range	=	ACC_PMU_RANGE_16;
	sensor_config.gyro_rate		=	GYRO_ODR_1000;
	sensor_config.gyro_range	=	GYRO_RANGE_RANGE_2000;
	sensor_config.mag_rate		=	MAG_PWR_CR2_ODR_20;
	sensor_config.mag_range_xy	=	MAG_REP_XY_HIGH_ACCURACY_PRESET_REPXY;
	sensor_config.mag_range_z	=	MAG_REP_Z_HIGH_ACCURACY_PRESET_REPZ;

	SSTATUS sensor_status;
	do{
		sensor_status	=	sensor_initialize(&sensor_config);
	}while (sensor_status != SENS_OK);

	/* Initialize GNSS */

	/* Initialize EXTI */
	exti_initialize();

	/* Indicate End of Initialization */
	STM_EVAL_LEDOn(LED3);

	/* Data logging loop */
	while (	file_flag.log_enabled == 1)
	{
		STM_EVAL_LEDOn(LED6);
		if ((volatile int) sensor_log_on == SENSOR_LOG_ON) {
			status = write_to_memory (
					&file_system,
					&file_pointer,
					f_err_code,
					filename,
					&bytes_written,
					sensor_address_to_log,
					sensor_bytes_to_log,
					&file_flag);
			sensor_log_on = SENSOR_LOG_OFF;
		}STM_EVAL_LEDOff(LED6);
	}
	if (file_flag.log_enabled == 0){
		status = write_to_memory (
				&file_system,
				&file_pointer,
				f_err_code,
				filename,
				&bytes_written,
				dummy,
				sizeof(dummy),
				&file_flag);
	}STM_EVAL_LEDOn(LED5);

	/* Infinite loop */
	while(1){

	}
}
